{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2023-05-12 00:40:33,410 DEBUG:\tCOMLOG_CLIENT:socket_connect()\tcreate socket\n",
      "2023-05-12 00:40:33,412 DEBUG:\tCOMLOG_CLIENT:socket_connect()\tClient connect: 10.37.0.105 , 53215\n",
      "2023-05-12 00:40:33,413 DEBUG:\tCOMLOG_CLIENT:client_worker()\tClient asked for: ACQUIRE_Z\n",
      "2023-05-12 00:40:33,414 DEBUG:\tCOMLOG_CLIENT:_send_package()\tSent BYTES TO SEND: 195\n",
      "2023-05-12 00:40:33,456 DEBUG:\tCOMLOG_CLIENT:client_worker()\tConnection closed successfully\n",
      "2023-05-12 00:40:33,457 ERROR:\tCOMLOG_CLIENT:execute_TEST()\tThis command did not work\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 67, in _send_package\n",
      "    answer = unpack(conn.recv(TCP_BUFFER))\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 12, in unpack\n",
      "    return pickle.loads(codecs.decode(package, encoding=CODEC)) #protocol is detected automatically\n",
      "EOFError: Ran out of input\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 567, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 330, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\runpy.py\", line 184, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\ioloop.py\", line 888, in start\n",
      "    handler_func(fd_obj, events)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 281, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 232, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 397, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 208, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 533, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2714, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2818, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2878, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-4be77d553f0b>\", line 4, in <module>\n",
      "    stack = meteor.execute_TEST()\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\", line 55, in execute_TEST\n",
      "    answer = self._execute_command()[-1]\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\", line 92, in _execute_command\n",
      "    result = client_worker(self.socket,package)\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\client_worker.py\", line 17, in client_worker\n",
      "    _send_package(conn,pkg,logger=logger_client)\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 113, in _send_package\n",
      "    logger.error('Exception:', ex, )\n",
      "Message: 'Exception:'\n",
      "Arguments: (EOFError('Ran out of input',),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 67, in _send_package\n",
      "    answer = unpack(conn.recv(TCP_BUFFER))\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 12, in unpack\n",
      "    return pickle.loads(codecs.decode(package, encoding=CODEC)) #protocol is detected automatically\n",
      "EOFError: Ran out of input\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 567, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 330, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\runpy.py\", line 184, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\ioloop.py\", line 888, in start\n",
      "    handler_func(fd_obj, events)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 281, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 232, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 397, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 208, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 533, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2714, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2818, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2878, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-4be77d553f0b>\", line 4, in <module>\n",
      "    stack = meteor.execute_TEST()\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\", line 55, in execute_TEST\n",
      "    answer = self._execute_command()[-1]\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\", line 92, in _execute_command\n",
      "    result = client_worker(self.socket,package)\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\client_worker.py\", line 17, in client_worker\n",
      "    _send_package(conn,pkg,logger=logger_client)\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 113, in _send_package\n",
      "    logger.error('Exception:', ex, )\n",
      "Message: 'Exception:'\n",
      "Arguments: (EOFError('Ran out of input',),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 123, in _receive_package\n",
      "    pkg = unpack(conn.recv(TCP_BUFFER))\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 12, in unpack\n",
      "    return pickle.loads(codecs.decode(package, encoding=CODEC)) #protocol is detected automatically\n",
      "EOFError: Ran out of input\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 567, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 330, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\runpy.py\", line 184, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\ioloop.py\", line 888, in start\n",
      "    handler_func(fd_obj, events)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 281, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 232, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 397, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 208, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 533, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2714, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2818, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2878, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-4be77d553f0b>\", line 4, in <module>\n",
      "    stack = meteor.execute_TEST()\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\", line 55, in execute_TEST\n",
      "    answer = self._execute_command()[-1]\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\", line 92, in _execute_command\n",
      "    result = client_worker(self.socket,package)\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\client_worker.py\", line 18, in client_worker\n",
      "    conn, pkg = _receive_package(conn,logger=logger_client)\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 173, in _receive_package\n",
      "    logger.error('Exception:', ex, )\n",
      "Message: 'Exception:'\n",
      "Arguments: (EOFError('Ran out of input',),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 123, in _receive_package\n",
      "    pkg = unpack(conn.recv(TCP_BUFFER))\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 12, in unpack\n",
      "    return pickle.loads(codecs.decode(package, encoding=CODEC)) #protocol is detected automatically\n",
      "EOFError: Ran out of input\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 567, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 330, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\runpy.py\", line 184, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\ioloop.py\", line 888, in start\n",
      "    handler_func(fd_obj, events)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 281, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 232, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 397, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 208, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 533, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2714, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2818, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2878, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-4be77d553f0b>\", line 4, in <module>\n",
      "    stack = meteor.execute_TEST()\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\", line 55, in execute_TEST\n",
      "    answer = self._execute_command()[-1]\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\", line 92, in _execute_command\n",
      "    result = client_worker(self.socket,package)\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\client_worker.py\", line 18, in client_worker\n",
      "    conn, pkg = _receive_package(conn,logger=logger_client)\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 173, in _receive_package\n",
      "    logger.error('Exception:', ex, )\n",
      "Message: 'Exception:'\n",
      "Arguments: (EOFError('Ran out of input',),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\client_worker.py\", line 18, in client_worker\n",
      "    conn, pkg = _receive_package(conn,logger=logger_client)\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 177, in _receive_package\n",
      "    return conn, package\n",
      "UnboundLocalError: local variable 'package' referenced before assignment\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 567, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 330, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\runpy.py\", line 184, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\ioloop.py\", line 888, in start\n",
      "    handler_func(fd_obj, events)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 281, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 232, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 397, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 208, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 533, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2714, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2818, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2878, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-4be77d553f0b>\", line 4, in <module>\n",
      "    stack = meteor.execute_TEST()\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\", line 55, in execute_TEST\n",
      "    answer = self._execute_command()[-1]\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\", line 92, in _execute_command\n",
      "    result = client_worker(self.socket,package)\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\client_worker.py\", line 35, in client_worker\n",
      "    logger_client.exception('Exception:', ex, )\n",
      "Message: 'Exception:'\n",
      "Arguments: (UnboundLocalError(\"local variable 'package' referenced before assignment\",),)\n",
      "--- Logging error ---\n",
      "Traceback (most recent call last):\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\client_worker.py\", line 18, in client_worker\n",
      "    conn, pkg = _receive_package(conn,logger=logger_client)\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\package_exchange.py\", line 177, in _receive_package\n",
      "    return conn, package\n",
      "UnboundLocalError: local variable 'package' referenced before assignment\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 980, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 830, in format\n",
      "    return fmt.format(record)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 567, in format\n",
      "    record.message = record.getMessage()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\logging\\__init__.py\", line 330, in getMessage\n",
      "    msg = msg % self.args\n",
      "TypeError: not all arguments converted during string formatting\n",
      "Call stack:\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\runpy.py\", line 184, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\traitlets\\config\\application.py\", line 658, in launch_instance\n",
      "    app.start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 478, in start\n",
      "    self.io_loop.start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\ioloop.py\", line 177, in start\n",
      "    super(ZMQIOLoop, self).start()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\ioloop.py\", line 888, in start\n",
      "    handler_func(fd_obj, events)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 440, in _handle_events\n",
      "    self._handle_recv()\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 472, in _handle_recv\n",
      "    self._run_callback(callback, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\zmq\\eventloop\\zmqstream.py\", line 414, in _run_callback\n",
      "    callback(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\tornado\\stack_context.py\", line 277, in null_wrapper\n",
      "    return fn(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 281, in dispatcher\n",
      "    return self.dispatch_shell(stream, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 232, in dispatch_shell\n",
      "    handler(stream, idents, msg)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 397, in execute_request\n",
      "    user_expressions, allow_stdin)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 208, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 533, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2714, in run_cell\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2818, in run_ast_nodes\n",
      "    if self.run_code(code, result):\n",
      "  File \"c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2878, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-2-4be77d553f0b>\", line 4, in <module>\n",
      "    stack = meteor.execute_TEST()\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\", line 55, in execute_TEST\n",
      "    answer = self._execute_command()[-1]\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\", line 92, in _execute_command\n",
      "    result = client_worker(self.socket,package)\n",
      "  File \"d:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\communication\\client_worker.py\", line 35, in client_worker\n",
      "    logger_client.exception('Exception:', ex, )\n",
      "Message: 'Exception:'\n",
      "Arguments: (UnboundLocalError(\"local variable 'package' referenced before assignment\",),)\n"
     ]
    },
    {
     "ename": "UnboundLocalError",
     "evalue": "local variable 'answer' referenced before assignment",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mUnboundLocalError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-2-4be77d553f0b>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[0mmeteor\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mClient\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 4\u001b[1;33m \u001b[0mstack\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mmeteor\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexecute_TEST\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32md:\\User Data\\Johann\\SerialFIB-MeteorIntegrationVersion\\src\\FLM_client.py\u001b[0m in \u001b[0;36mexecute_TEST\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m     57\u001b[0m                         \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mlogger\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0merror\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m'This command did not work'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     58\u001b[0m                 \u001b[1;32mfinally\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 59\u001b[1;33m                         \u001b[1;32mreturn\u001b[0m \u001b[0manswer\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     60\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     61\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mUnboundLocalError\u001b[0m: local variable 'answer' referenced before assignment"
     ]
    }
   ],
   "source": [
    "from src.FLM_client import Client\n",
    "\n",
    "meteor = Client()\n",
    "stack = meteor.execute_TEST()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "stack = stack[0]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Warning: Cannot change to a different GUI toolkit: notebook. Using qt instead.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "c:\\Program Files\\Python35\\envs\\AutoScript\\lib\\site-packages\\matplotlib\\axes\\_base.py:2903: UserWarning: Attempting to set identical left==right results\n",
      "in singular transformations; automatically expanding.\n",
      "left=0, right=0\n",
      "  'left=%s, right=%s') % (left, right))\n"
     ]
    }
   ],
   "source": [
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.widgets import Slider\n",
    "%matplotlib notebook\n",
    "\n",
    "time, num_slices, num_channels, height, width = stack.shape\n",
    "\n",
    "fig, ax = plt.subplots()\n",
    "plt.subplots_adjust(bottom=0.15)\n",
    "\n",
    "# Initialize the slice and channel indices\n",
    "slice_idx = 0\n",
    "channel_idx = 0\n",
    "\n",
    "# Plot the initial slice\n",
    "img = ax.imshow(stack[0,slice_idx, channel_idx], cmap='gray')\n",
    "\n",
    "# Create a slider for the slice index\n",
    "ax_slice = plt.axes([0.15, 0.05, 0.7, 0.03])\n",
    "slider_slice = Slider(ax_slice, 'Slice', 0, num_slices - 1, valinit=slice_idx)\n",
    "\n",
    "# Create a slider for the channel index\n",
    "ax_channel = plt.axes([0.15, 0.1, 0.7, 0.03])\n",
    "slider_channel = Slider(ax_channel, 'Channel', 0, num_channels - 1, valinit=channel_idx)\n",
    "\n",
    "def update(val):\n",
    "    #nonlocal slice_idx, channel_idx, img\n",
    "\n",
    "    # Get the updated slice and channel indices\n",
    "    slice_idx = int(slider_slice.val)\n",
    "    channel_idx = int(slider_channel.val)\n",
    "\n",
    "    # Update the displayed image\n",
    "    img.set_data(stack[0, slice_idx, channel_idx])\n",
    "    fig.canvas.draw()\n",
    "\n",
    "slider_slice.on_changed(update)\n",
    "slider_channel.on_changed(update)\n",
    "\n",
    "plt.show()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.5.2 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.5.2"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "206f9c05e78a8c5fc0d13d6cfca9781bd9bf874b8e5991367cf688e9d4bf5863"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
